name: firebase_auth_rest_example
description: firebase_auth_rest example
version: 0.0.1
homepage: https://github.com/Skycoder42/firebase_auth_rest

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  lint: ^1.2.0
