include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "build/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    missing_required_param: error

lint:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: true
    unawaited_futures: true
