include: package:dart_test_tools/package.yaml
plugins:
  dart_test_tools: ^7.0.1
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - test/integration/test_config_js.dart
