name: CI/CD

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      panaScoreThreshold: 10
      unitTestPaths: -P unit
      coverageExclude: >-
        "**/*.g.dart"
        "**/*.freezed.dart"
      integrationTestPaths: -P integration
    secrets:
      integrationTestEnvVars: |
        FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    permissions:
      contents: write
      actions: write
    with:
      publishWorkflow: cd.yaml
