name: Github pages documentation

on:
  push:
    - tags

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
      - uses: actions/checkout@v2
      - run: pub get
      - run: pub run build_runner build
      - run: dartdoc
      - name: upload doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: doc/api
          commit_message: ${{github.ref}}
